In [ ]:
!pip list

In [ ]:
import pandas
pandas.__version__

## Syntax for installing any package in python

- !pip install package_name

In [ ]:
!pip install pandas

## To upgrade any package using jupyter notebook

- !pip install package_name --upgrade

In [ ]:
!pip install pandas --upgrade

In [1]:
import pandas 
pandas.__version__

'1.5.0'

## Importing a file using pandas

- variable_name = pd.read_csv(file_name or file path)

In [11]:
import pandas as pd
data = pd.read_csv('C:\\Users\\AMANT\\OneDrive\\Desktop\\EduBridge\\sales.csv', index_col = 'month')

In [12]:
data

eggs   salt   spam
month                     
Jan       47   12.0     17
Feb      110   50.0     31
Mar      221   89.0     72
Apr       77   87.0     20
May      132    NaN     52
Jun      205   60.0     55

In [15]:
type(data)

pandas.core.frame.DataFrame

In [13]:
import numpy as np
arr = np.array([1,2,3,4])

In [14]:
arr

array([1, 2, 3, 4])

In [16]:
import numpy as np

#create array of arrays
all_arrays = np.array([[10, 20, 30, 40, 50],
                       [60, 70, 80, 90, 100],
                       [110, 120, 130, 140, 150]])

#view array of arrays
print(all_arrays)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


## Pandas Series Object

In [18]:
ser = pd.Series([1,2,3,4,5])
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
type(ser)

pandas.core.series.Series

- Series is one dimensional object which means it will always have only one column and multiple rows.

In [20]:
ser1 = pd.Series([10,20,30,40,50])
ser1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [21]:
type(ser1)

pandas.core.series.Series

- DataFrame is 2 D object which means that it can have multiple rows and multiple columns

In [27]:
dataframe = pd.DataFrame({'cities' : ['UP', 'MH', 'Bihar', 'Kar'], 'population' : [1000, 2000, 3000, 4000]})
dataframe

cities  population
0     UP        1000
1     MH        2000
2  Bihar        3000
3    Kar        4000

In [28]:
type(dataframe)

pandas.core.frame.DataFrame

In [30]:
dataframe.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['cities', 'population'], dtype='object')]

## dataframe.index will give only the row index in the output

In [31]:
dataframe.index

RangeIndex(start=0, stop=4, step=1)

In [32]:
data

eggs   salt   spam
month                     
Jan       47   12.0     17
Feb      110   50.0     31
Mar      221   89.0     72
Apr       77   87.0     20
May      132    NaN     52
Jun      205   60.0     55

## dataframe.axes will give the row index and also the column index

In [33]:
data.axes

[Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], dtype='object', name='month'),
 Index([' eggs', ' salt', ' spam'], dtype='object')]

In [35]:
dataframe = pd.DataFrame({'cities' : ['UP', 'MH', 'Bihar', 'Kar'], 'population' : [1000, 2000, 3000, 4000]})
dataframe

cities  population
0     UP        1000
1     MH        2000
2  Bihar        3000
3    Kar        4000

In [36]:
data

eggs   salt   spam
month                     
Jan       47   12.0     17
Feb      110   50.0     31
Mar      221   89.0     72
Apr       77   87.0     20
May      132    NaN     52
Jun      205   60.0     55

In [37]:
data.size

18