In [1]:
import numpy as np

## Creating a numpy array

In [2]:
arr = np.array([10, 20, 30, 40])
arr

array([10, 20, 30, 40])

In [3]:
type(arr)

numpy.ndarray

## Creating a numpy matrix

In [4]:
lst = [[25, 35, 45, 55], [20, 30, 40, 50], [100, 200, 300, 400]]
arr1 = np.array(lst)
arr1

array([[ 25,  35,  45,  55],
       [ 20,  30,  40,  50],
       [100, 200, 300, 400]])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr

array([10, 20, 30, 40])

## Numpy functions

In [7]:
np.min(arr)

10

In [8]:
np.max(arr)

40

In [9]:
## Converts rows into columns and columns into rows of the original array

np.transpose(arr1)

array([[ 25,  20, 100],
       [ 35,  30, 200],
       [ 45,  40, 300],
       [ 55,  50, 400]])

In [10]:
arr2 = np.array([-2, 3, -4, 9, -8])
arr2

array([-2,  3, -4,  9, -8])

In [11]:
## absolute function is used to convert any number into a positive number

np.abs(arr2)

array([2, 3, 4, 9, 8])

In [12]:
arr3 = np.array([2.5, 10.5, 15.75, 16.25])
arr3

array([ 2.5 , 10.5 , 15.75, 16.25])

In [13]:
## Floor function converts the number into the lowest value near to it

np.floor(arr3)

array([ 2., 10., 15., 16.])

In [14]:
arr4 = np.random.randint(5, 25 ,50)
arr4

array([18,  8, 18, 13, 22, 12, 21,  7, 16, 21, 23, 10, 11, 24, 13, 24, 15,
       15, 20, 22, 17, 18, 22, 17, 14, 23,  6,  5, 21, 13,  7, 23, 22, 24,
       21, 14, 18,  9, 13, 23, 10, 19, 17, 10,  9, 12, 12, 12, 18,  6])

## Syntax for randint function

In [15]:
arr5 = np.random.randint(5,15, 6)
arr5

array([ 5,  6,  8, 13, 10, 12])

In [16]:
arr6 = np.random.randint(100, 125, 6)
arr6

array([111, 108, 109, 115, 106, 106])

In [17]:
np.add(arr5, arr6)

array([116, 114, 117, 128, 116, 118])

In [18]:
np.multiply(arr5, arr6)

array([ 555,  648,  872, 1495, 1060, 1272])

In [19]:
arr5

array([ 5,  6,  8, 13, 10, 12])

In [20]:
np.cumsum(arr5)

array([ 5, 11, 19, 32, 42, 54], dtype=int32)

In [21]:
np.cumprod(arr5)

array([     5,     30,    240,   3120,  31200, 374400], dtype=int32)

In [26]:
np.random.shuffle(arr5)

In [27]:
arr

array([10, 20, 30, 40])

In [30]:
arr10 = np.random.randint(5, 15, 5)
arr10

array([ 6, 12,  7, 12,  5])

In [31]:
np.random.shuffle(arr10)

In [32]:
arr10

array([12,  7,  5, 12,  6])

In [ ]:
1. binomial
2. polyfit
3. histogram

In [93]:
a = np.random.randint(0, 100, 50)
a

array([ 7, 11, 27,  6, 51, 29, 61, 27, 20, 34, 57, 26, 11, 52, 86, 92, 14,
       89, 84, 21, 66, 23, 72, 64, 97, 86,  6, 77, 59, 55, 51, 53, 29,  6,
       96, 12, 54, 42, 62, 77, 96, 80, 11, 68,  5,  4, 65, 33, 79, 41])

In [94]:
np.histogram(a)

(array([10,  3,  6,  3,  1,  8,  6,  3,  5,  5], dtype=int64),
 array([ 4. , 13.3, 22.6, 31.9, 41.2, 50.5, 59.8, 69.1, 78.4, 87.7, 97. ]))

In [99]:
n, p = 10, 0.5   ## I am flipping a coin is done 10 times and p is probability which is 0.5
s = np.random.binomial(n, p, 100)
s

array([5, 8, 9, 3, 3, 4, 5, 4, 3, 5, 6, 6, 6, 6, 2, 4, 6, 6, 7, 7, 5, 1,
       7, 5, 3, 7, 4, 8, 4, 6, 4, 6, 3, 7, 3, 5, 8, 2, 4, 7, 3, 5, 6, 3,
       6, 7, 1, 4, 6, 3, 4, 5, 4, 6, 4, 1, 6, 7, 6, 3, 6, 6, 6, 4, 4, 6,
       4, 5, 2, 6, 6, 3, 6, 8, 3, 3, 3, 4, 7, 7, 6, 7, 3, 4, 4, 5, 4, 5,
       5, 4, 1, 6, 3, 7, 7, 4, 6, 2, 3, 3])

In [100]:
s.size

100

## polyfit()
- Used to least square polynomial fit

In [102]:
x = np.array([0.0,1.0,2.0,3.0,4.0,5.0])
y = np.array([0.0,0.8,0.9,0.1,-0.8,-1.0])
z = np.polyfit(x, y, 2)
z

array([-0.16071429,  0.50071429,  0.22142857])

## Creating a numpy arrary from list

In [34]:
lst = [[10, 20, 30], [30, 40, 50]]
arr = np.array(lst)
arr

array([[10, 20, 30],
       [30, 40, 50]])

In [35]:
type(arr)

numpy.ndarray

In [36]:
arr1 = np.random.randint(10, 20, 5)
arr1

array([14, 10, 18, 11, 14])

In [38]:
arr2 = np.random.randint(25, 50, 5)
arr2

array([27, 34, 34, 38, 38])

## Element wise addition

In [39]:
arr3 = arr1 + arr2

In [40]:
arr3

array([41, 44, 52, 49, 52])

In [41]:
type(arr3)

numpy.ndarray

## Broadcasting casting operation

In [42]:
lst = [1, 2, 3, 4]
lst

[1, 2, 3, 4]

In [43]:
lst * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [45]:
x = np.array([10, 20, 30, 40])
x

array([10, 20, 30, 40])

In [46]:
x * 3

array([ 30,  60,  90, 120])

In [47]:
x

array([10, 20, 30, 40])

In [48]:
x.shape

(4,)

In [49]:
arr

array([[10, 20, 30],
       [30, 40, 50]])

In [51]:
arr.shape

(2, 3)

## Homogeneous multidimensional array

In [52]:
lst = [10, 'hello', 25, 35.5, 'anant']
lst

[10, 'hello', 25, 35.5, 'anant']

In [54]:
a = np.array(lst)
a

array(['10', 'hello', '25', '35.5', 'anant'], dtype='<U32')

In [55]:
a1 = np.array([10, 20, 35.75, 45])
a1

array([10.  , 20.  , 35.75, 45.  ])

## Numpy array attributes

In [56]:
arr

array([[10, 20, 30],
       [30, 40, 50]])

In [63]:
arr.shape

(2, 3)

In [58]:
## ndim = number of dimensions

arr.ndim

2

In [59]:
arr.size

6

In [60]:
arr5

array([ 5,  8, 10, 13, 12,  6])

In [61]:
arr5.size

6

In [65]:
arr5.shape

(6,)

In [66]:
arr

array([[10, 20, 30],
       [30, 40, 50]])

In [67]:
type(arr)

numpy.ndarray

In [68]:
arr.dtype

dtype('int32')

In [69]:
a

array(['10', 'hello', '25', '35.5', 'anant'], dtype='<U32')

In [70]:
a.dtype

dtype('<U32')

In [72]:
arr3 = np.array([2.5, 10.5, 15.75, 16.25])
arr3

array([ 2.5 , 10.5 , 15.75, 16.25])

In [73]:
arr3.dtype

dtype('float64')

In [75]:
arr3.itemsize

8

In [76]:
arr

array([[10, 20, 30],
       [30, 40, 50]])

In [77]:
arr.itemsize

4

In [79]:
print(arr.data)

## Statistical function on array

In [80]:
arr1 = np.random.randint(10, 20, 5)
arr1

array([17, 16, 16, 14, 16])

In [81]:
np.mean(arr1)

15.8

In [82]:
np.sum(arr1)

79

In [83]:
np.sum(arr1)/5

15.8

## Median

- For array with odd elements, the median will always be the mid value
- For array with even elements, the median will always be the average of 2 mid values of sorted array

In [84]:
np.median(arr1)

16.0

In [85]:
arr2 = np.random.randint(10, 20, 6)
arr2

array([19, 12, 19, 18, 17, 10])

In [86]:
np.median(arr2)

17.5

In [89]:
arr

array([[10, 20, 30],
       [30, 40, 50]])

In [90]:
np.corrcoef(arr)

array([[1., 1.],
       [1., 1.]])

In [91]:
np.cov(arr)

array([[100., 100.],
       [100., 100.]])